spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.101.200:3306/jinhuaapp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jinhua2020
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 1
    defaultAutoCommit: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

#60.205.253.198
  redis:
    host: 192.168.101.200
    port: 6379
    password: jinhua2020
    timeout: 5000
    pool:
      minIdle: 10
      maxIdle: 10
      maxTotal: 100
      maxWaitMillis: 5000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

